name: event_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1
  feather_icons: ^1.2.0
  intl: ^0.18.1
  dio: ^5.0.1
  get_storage: ^2.0.3
  carousel_slider: ^4.2.1
  
  image_picker: ^0.8.7+3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
